# Stage 1: Build the application
FROM node:latest as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Create a smaller image for production
FROM node:latest as production

WORKDIR /app

COPY --from=build /app/dist ./dist

RUN npm install -g serve

EXPOSE 5000

CMD ["npx", "serve", "-s", "dist"]